image: jgoldfar/julia-docker:v07-latest

pipelines:
  default:
    - step:
        script:
          - julia --project=. -e 'using Pkg; Pkg.instantiate()'
          - julia --project=. -e 'using Pkg; Pkg.test()'
