authors = ["Jonathan Goldfarb <jgoldfar@gmail.com>"]
name = "MISPExamples"
uuid = "c1e558f6-6b4a-11e8-0037-fbb02674179a"
version = "0.1.0"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
